#Production phase

security.jwt.secret-key=${jwt_secret}
security.jwt.expiration-time=${expiration_time}

spring.datasource.url= ${database_url}
spring.datasource.username=postgres
spring.datasource.password=${db_password}