spring.application.name=springauth
server.port = 8080
#PostgresDatabase Configuration

#------------------------
#Hibernate Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.profiles.active=${ENV:dev}

sendgrid.api.key=${SENDGRID_API_KEY}


logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.com.yourpackage=DEBUG

spring.sql.init.mode=always
